apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omniscope

resources:
- ../../base

images:
- name: omniscope/backend
  newTag: v1.0.0
- name: omniscope/frontend
  newTag: v1.0.0

configMapGenerator:
- name: omniscope-config
  behavior: merge
  literals:
  - log-level=warning
  - environment=production
  - enable-monitoring=true
  - enable-tracing=true
