apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omniscope-dev

resources:
- ../../base

namePrefix: dev-

replicas:
- name: omniscope-backend
  count: 1
- name: omniscope-frontend
  count: 1
- name: dask-worker
  count: 2

images:
- name: omniscope/backend
  newTag: dev
- name: omniscope/frontend
  newTag: dev

configMapGenerator:
- name: omniscope-config
  behavior: merge
  literals:
  - log-level=debug
  - environment=development

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "1Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "2Gi"
  target:
    kind: Deployment
    name: omniscope-backend
